const WORKERS = [
  {
    id: 1,
    name: "Wanjiru Kamau",
    skill: "Electrician",
    verified: true,
    price: "KES 2,500 – 7,000 / job",
    photo: "https://randomuser.me/api/portraits/women/36.jpg",
    location: "Westlands, Nairobi",
    bio: "Certified electrician with 8 years of experience wiring homes and small offices. I handle installations, fault-finding, and safety inspections. No job too small.",
    rating: 4.8,
    jobSuccess: 100,
    hoursPerWeek: "More than 30 hrs/week",
    totalEarnings: "KES 900K+",
    jobsCompleted: 36,
    hoursWorked: 1492,
    languages: [
      { name: "English", level: "Fluent" },
      { name: "Swahili", level: "Native" },
    ],
    workHistory: [
      { title: "Full rewire of 3-bedroom bungalow", rating: 5, dateRange: "Jan 2025 - Feb 2025", price: "KES 18,000", priceType: "Fixed price" },
      { title: "Fuse box replacement and safety inspection", rating: 5, dateRange: "Nov 2024 - Nov 2024", price: "KES 6,500", priceType: "Fixed price" },
    ],
    reviews: [
      { author: "Kevin O.", rating: 5, comment: "Fixed my fuse box same day. Very professional." },
      { author: "Linda W.", rating: 5, comment: "Tidy work and explained everything clearly." },
      { author: "Brian K.", rating: 4, comment: "Good job, arrived a little late but worth it." },
    ],
  },
  {
    id: 2,
    name: "Kiptoo Ruto",
    skill: "Electrician",
    verified: true,
    price: "KES 2,200 – 6,800 / job",
    photo: "https://randomuser.me/api/portraits/men/12.jpg",
    location: "Kasarani, Nairobi",
    bio: "Residential and commercial electrician focused on clean, code-compliant wiring and quick fault diagnosis.",
    rating: 4.6,
    jobSuccess: 96,
    hoursPerWeek: "More than 30 hrs/week",
    totalEarnings: "KES 500K+",
    jobsCompleted: 24,
    hoursWorked: 980,
    languages: [
      { name: "English", level: "Fluent" },
      { name: "Swahili", level: "Native" },
    ],
    workHistory: [
      { title: "Office lighting upgrade", rating: 5, dateRange: "Mar 2025 - Mar 2025", price: "KES 9,200", priceType: "Fixed price" },
      { title: "Generator changeover switch install", rating: 4, dateRange: "Dec 2024 - Dec 2024", price: "KES 7,000", priceType: "Fixed price" },
    ],
    reviews: [
      { author: "Alice N.", rating: 5, comment: "Sorted our office wiring fast, no comebacks." },
    ],
  },
  {
    id: 3,
    name: "Achieng Nyambura",
    skill: "Plumber",
    verified: true,
    price: "KES 1,800 – 6,000 / job",
    photo: "https://randomuser.me/api/portraits/women/47.jpg",
    location: "Embakasi, Nairobi",
    bio: "Plumber handling leak repairs, borehole connections, and bathroom installations across Nairobi's eastlands.",
    rating: 4.7,
    jobSuccess: 98,
    hoursPerWeek: "More than 30 hrs/week",
    totalEarnings: "KES 650K+",
    jobsCompleted: 31,
    hoursWorked: 1120,
    languages: [
      { name: "English", level: "Conversational" },
      { name: "Swahili", level: "Native" },
    ],
    workHistory: [
      { title: "Bathroom re-piping", rating: 5, dateRange: "Feb 2025 - Feb 2025", price: "KES 15,000", priceType: "Fixed price" },
      { title: "Kitchen sink and tap installation", rating: 4, dateRange: "Oct 2024 - Oct 2024", price: "KES 4,500", priceType: "Fixed price" },
    ],
    reviews: [
      { author: "Grace M.", rating: 5, comment: "Found and fixed a hidden leak others missed." },
    ],
  },
  {
    id: 4,
    name: "Kevin Mwangi",
    skill: "Plumber",
    verified: false,
    price: "KES 2,000 – 6,500 / job",
    photo: "https://randomuser.me/api/portraits/men/23.jpg",
    location: "Ngong Road, Nairobi",
    bio: "General plumbing repairs and installations, available for emergency call-outs on short notice.",
    rating: 4.3,
    jobSuccess: 90,
    hoursPerWeek: "Less than 30 hrs/week",
    totalEarnings: "KES 220K+",
    jobsCompleted: 14,
    hoursWorked: 410,
    languages: [
      { name: "English", level: "Fluent" },
      { name: "Swahili", level: "Native" },
    ],
    workHistory: [
      { title: "Emergency leak repair", rating: 4, dateRange: "Apr 2025 - Apr 2025", price: "KES 3,200", priceType: "Fixed price" },
      { title: "Water heater installation", rating: 4, dateRange: "Jan 2025 - Jan 2025", price: "KES 6,000", priceType: "Fixed price" },
    ],
    reviews: [
      { author: "Peter N.", rating: 4, comment: "Came out same evening, sorted the leak." },
    ],
  },
  {
    id: 5,
    name: "Njeri Kariuki",
    skill: "Carpenter",
    verified: true,
    price: "KES 3,500 – 11,000 / job",
    photo: "https://randomuser.me/api/portraits/women/65.jpg",
    location: "Kilimani, Nairobi",
    bio: "Furniture maker and fitted-wardrobe specialist. I design pieces around the space rather than forcing standard sizes.",
    rating: 4.9,
    jobSuccess: 100,
    hoursPerWeek: "More than 30 hrs/week",
    totalEarnings: "KES 1.1M+",
    jobsCompleted: 42,
    hoursWorked: 1780,
    languages: [
      { name: "English", level: "Fluent" },
      { name: "Swahili", level: "Native" },
    ],
    workHistory: [
      { title: "Built-in wardrobe for master bedroom", rating: 5, dateRange: "Feb 2025 - Mar 2025", price: "KES 32,000", priceType: "Fixed price" },
      { title: "Custom TV unit and shelving", rating: 5, dateRange: "Dec 2024 - Dec 2024", price: "KES 21,000", priceType: "Fixed price" },
    ],
    reviews: [
      { author: "Sarah K.", rating: 5, comment: "Exceptional finish, exactly what we sketched out." },
    ],
  },
  {
    id: 6,
    name: "Baraka Mwadime",
    skill: "Carpenter",
    verified: true,
    price: "KES 3,000 – 9,500 / job",
    photo: "https://randomuser.me/api/portraits/men/41.jpg",
    location: "Lang'ata, Nairobi",
    bio: "General carpentry and door/window frame repairs, with a focus on quick turnarounds for rental units.",
    rating: 4.4,
    jobSuccess: 93,
    hoursPerWeek: "Less than 30 hrs/week",
    totalEarnings: "KES 300K+",
    jobsCompleted: 19,
    hoursWorked: 640,
    languages: [
      { name: "English", level: "Conversational" },
      { name: "Swahili", level: "Native" },
    ],
    workHistory: [
      { title: "Door and frame replacement, 4 units", rating: 4, dateRange: "Mar 2025 - Mar 2025", price: "KES 14,000", priceType: "Fixed price" },
    ],
    reviews: [
      { author: "Moses T.", rating: 4, comment: "Solid work, kept to the timeline." },
    ],
  },
  {
    id: 7,
    name: "Faith Chebet",
    skill: "Painter",
    verified: true,
    price: "KES 2,200 – 8,500 / job",
    photo: "https://randomuser.me/api/portraits/women/58.jpg",
    location: "Ruaka, Nairobi",
    bio: "Interior and exterior painter with an eye for clean lines and colour matching for resale-ready finishes.",
    rating: 4.7,
    jobSuccess: 97,
    hoursPerWeek: "More than 30 hrs/week",
    totalEarnings: "KES 480K+",
    jobsCompleted: 27,
    hoursWorked: 890,
    languages: [
      { name: "English", level: "Fluent" },
      { name: "Swahili", level: "Native" },
    ],
    workHistory: [
      { title: "Full interior repaint, 3-bed apartment", rating: 5, dateRange: "Jan 2025 - Jan 2025", price: "KES 22,000", priceType: "Fixed price" },
      { title: "Exterior perimeter wall painting", rating: 4, dateRange: "Nov 2024 - Nov 2024", price: "KES 16,000", priceType: "Fixed price" },
    ],
    reviews: [
      { author: "Janet A.", rating: 5, comment: "Neat edges, no drips, finished on schedule." },
    ],
  },
  {
    id: 8,
    name: "Dennis Omondi",
    skill: "Painter",
    verified: false,
    price: "KES 2,000 – 7,000 / job",
    photo: "https://randomuser.me/api/portraits/men/77.jpg",
    location: "South B, Nairobi",
    bio: "Affordable, reliable painting for homes and small shops, with weekend availability.",
    rating: 4.1,
    jobSuccess: 88,
    hoursPerWeek: "Less than 30 hrs/week",
    totalEarnings: "KES 150K+",
    jobsCompleted: 11,
    hoursWorked: 320,
    languages: [
      { name: "English", level: "Conversational" },
      { name: "Swahili", level: "Native" },
    ],
    workHistory: [
      { title: "Shopfront repaint", rating: 4, dateRange: "Feb 2025 - Feb 2025", price: "KES 8,000", priceType: "Fixed price" },
    ],
    reviews: [
      { author: "Wesley O.", rating: 4, comment: "Fair price, decent finish." },
    ],
  },
  {
    id: 9,
    name: "Mutua Kioko",
    skill: "Painter",
    verified: true,
    price: "KES 2,000 – 9,000 / job",
    photo: "https://randomuser.me/api/portraits/men/55.jpg",
    location: "Nyali, Mombasa",
    bio: "Interior and exterior painting with attention to clean edges and durable finishes. I help you choose colours that match your space.",
    rating: 4.7,
    jobSuccess: 99,
    hoursPerWeek: "More than 30 hrs/week",
    totalEarnings: "KES 700K+",
    jobsCompleted: 33,
    hoursWorked: 1250,
    languages: [
      { name: "English", level: "Fluent" },
      { name: "Swahili", level: "Native" },
    ],
    workHistory: [
      { title: "Beachfront villa exterior repaint", rating: 5, dateRange: "Feb 2025 - Mar 2025", price: "KES 45,000", priceType: "Fixed price" },
      { title: "Living room and hallway repaint", rating: 4, dateRange: "Dec 2024 - Dec 2024", price: "KES 12,000", priceType: "Fixed price" },
    ],
    reviews: [
      { author: "Susan M.", rating: 5, comment: "Transformed our living room. Spotless finish." },
      { author: "Peter N.", rating: 4, comment: "On time and neat." },
    ],
  },
  {
    id: 10,
    name: "Halima Juma",
    skill: "Electrician",
    verified: true,
    price: "KES 2,300 – 7,200 / job",
    photo: "https://randomuser.me/api/portraits/women/12.jpg",
    location: "Bamburi, Mombasa",
    bio: "Electrician specialising in solar backup setups and standard household wiring for coastal homes.",
    rating: 4.8,
    jobSuccess: 100,
    hoursPerWeek: "More than 30 hrs/week",
    totalEarnings: "KES 600K+",
    jobsCompleted: 29,
    hoursWorked: 1080,
    languages: [
      { name: "English", level: "Fluent" },
      { name: "Swahili", level: "Native" },
    ],
    workHistory: [
      { title: "Solar backup and inverter wiring", rating: 5, dateRange: "Mar 2025 - Mar 2025", price: "KES 28,000", priceType: "Fixed price" },
      { title: "Whole-house rewire", rating: 5, dateRange: "Sep 2024 - Oct 2024", price: "KES 24,000", priceType: "Fixed price" },
    ],
    reviews: [
      { author: "Fatuma R.", rating: 5, comment: "Explained the solar setup clearly, very patient." },
    ],
  },
  {
    id: 11,
    name: "Charo Mwakio",
    skill: "Electrician",
    verified: false,
    price: "KES 2,000 – 6,500 / job",
    photo: "https://randomuser.me/api/portraits/men/33.jpg",
    location: "Likoni, Mombasa",
    bio: "General electrical repairs and new installations for homes and small businesses.",
    rating: 4.2,
    jobSuccess: 91,
    hoursPerWeek: "Less than 30 hrs/week",
    totalEarnings: "KES 180K+",
    jobsCompleted: 13,
    hoursWorked: 360,
    languages: [
      { name: "English", level: "Conversational" },
      { name: "Swahili", level: "Native" },
    ],
    workHistory: [
      { title: "Shop rewiring and socket install", rating: 4, dateRange: "Jan 2025 - Jan 2025", price: "KES 9,500", priceType: "Fixed price" },
    ],
    reviews: [
      { author: "Ali H.", rating: 4, comment: "Got the job done, a bit of back and forth on timing." },
    ],
  },
  {
    id: 12,
    name: "Zawadi Salim",
    skill: "Plumber",
    verified: true,
    price: "KES 1,900 – 6,200 / job",
    photo: "https://randomuser.me/api/portraits/women/21.jpg",
    location: "Tudor, Mombasa",
    bio: "Plumbing installations and repairs, with experience fitting water tanks and pressure pumps.",
    rating: 4.6,
    jobSuccess: 97,
    hoursPerWeek: "More than 30 hrs/week",
    totalEarnings: "KES 420K+",
    jobsCompleted: 22,
    hoursWorked: 760,
    languages: [
      { name: "English", level: "Fluent" },
      { name: "Swahili", level: "Native" },
    ],
    workHistory: [
      { title: "Rooftop tank and pressure pump install", rating: 5, dateRange: "Feb 2025 - Feb 2025", price: "KES 19,000", priceType: "Fixed price" },
      { title: "Bathroom leak repair", rating: 4, dateRange: "Nov 2024 - Nov 2024", price: "KES 3,800", priceType: "Fixed price" },
    ],
    reviews: [
      { author: "Neema K.", rating: 5, comment: "Water pressure finally sorted after months of issues." },
    ],
  },
  {
    id: 13,
    name: "Omar Bakari",
    skill: "Carpenter",
    verified: true,
    price: "KES 3,200 – 10,500 / job",
    photo: "https://randomuser.me/api/portraits/men/8.jpg",
    location: "Kizingo, Mombasa",
    bio: "Custom furniture and coastal-style woodwork, including verandah seating and outdoor pieces.",
    rating: 4.8,
    jobSuccess: 98,
    hoursPerWeek: "More than 30 hrs/week",
    totalEarnings: "KES 550K+",
    jobsCompleted: 26,
    hoursWorked: 940,
    languages: [
      { name: "English", level: "Fluent" },
      { name: "Swahili", level: "Native" },
    ],
    workHistory: [
      { title: "Verandah seating set", rating: 5, dateRange: "Mar 2025 - Mar 2025", price: "KES 27,000", priceType: "Fixed price" },
      { title: "Kitchen cabinet refit", rating: 4, dateRange: "Dec 2024 - Jan 2025", price: "KES 19,500", priceType: "Fixed price" },
    ],
    reviews: [
      { author: "Hassan M.", rating: 5, comment: "Beautiful coastal-style finish, exactly what we wanted." },
    ],
  },
  {
    id: 14,
    name: "Rehema Athman",
    skill: "Carpenter",
    verified: false,
    price: "KES 3,000 – 9,000 / job",
    photo: "https://randomuser.me/api/portraits/women/72.jpg",
    location: "Mtwapa, Mombasa",
    bio: "Furniture repair and small joinery jobs, working out of a home workshop in Mtwapa.",
    rating: 4.3,
    jobSuccess: 92,
    hoursPerWeek: "Less than 30 hrs/week",
    totalEarnings: "KES 190K+",
    jobsCompleted: 15,
    hoursWorked: 480,
    languages: [
      { name: "English", level: "Conversational" },
      { name: "Swahili", level: "Native" },
    ],
    workHistory: [
      { title: "Dining table repair and refinish", rating: 4, dateRange: "Feb 2025 - Feb 2025", price: "KES 6,500", priceType: "Fixed price" },
    ],
    reviews: [
      { author: "Amina S.", rating: 4, comment: "Table looks brand new again." },
    ],
  },
  {
    id: 15,
    name: "Otieno Odhiambo",
    skill: "Plumber",
    verified: true,
    price: "KES 2,000 – 6,500 / job",
    photo: "https://randomuser.me/api/portraits/men/80.jpg",
    location: "Kisumu, Nyanza",
    bio: "Reliable plumber specialising in leak repairs, water heater installs, and bathroom fittings. Available on short notice for emergencies.",
    rating: 4.6,
    jobSuccess: 96,
    hoursPerWeek: "More than 30 hrs/week",
    totalEarnings: "KES 520K+",
    jobsCompleted: 25,
    hoursWorked: 910,
    languages: [
      { name: "English", level: "Fluent" },
      { name: "Swahili", level: "Native" },
    ],
    workHistory: [
      { title: "Water heater install and pipe insulation", rating: 5, dateRange: "Feb 2025 - Feb 2025", price: "KES 11,000", priceType: "Fixed price" },
      { title: "Emergency leak repair, apartment block", rating: 4, dateRange: "Dec 2024 - Dec 2024", price: "KES 4,200", priceType: "Fixed price" },
    ],
    reviews: [
      { author: "Mary A.", rating: 5, comment: "Stopped a leak that two others couldn't. Lifesaver." },
      { author: "Joseph M.", rating: 4, comment: "Fair price and clean work." },
    ],
  },
  {
    id: 16,
    name: "Brenda Anyango",
    skill: "Plumber",
    verified: true,
    price: "KES 1,800 – 5,800 / job",
    photo: "https://randomuser.me/api/portraits/women/19.jpg",
    location: "Milimani, Kisumu",
    bio: "Plumbing repairs and new bathroom fittings, working mostly around Milimani and Nyalenda.",
    rating: 4.5,
    jobSuccess: 94,
    hoursPerWeek: "More than 30 hrs/week",
    totalEarnings: "KES 340K+",
    jobsCompleted: 20,
    hoursWorked: 700,
    languages: [
      { name: "English", level: "Fluent" },
      { name: "Swahili", level: "Native" },
    ],
    workHistory: [
      { title: "Bathroom fittings replacement", rating: 5, dateRange: "Jan 2025 - Jan 2025", price: "KES 9,000", priceType: "Fixed price" },
    ],
    reviews: [
      { author: "Caren O.", rating: 4, comment: "Good communication, arrived when promised." },
    ],
  },
  {
    id: 17,
    name: "Collins Owino",
    skill: "Electrician",
    verified: true,
    price: "KES 2,100 – 6,900 / job",
    photo: "https://randomuser.me/api/portraits/men/64.jpg",
    location: "Nyalenda, Kisumu",
    bio: "Electrician handling home wiring, meter box upgrades, and appliance connections.",
    rating: 4.5,
    jobSuccess: 95,
    hoursPerWeek: "Less than 30 hrs/week",
    totalEarnings: "KES 260K+",
    jobsCompleted: 17,
    hoursWorked: 560,
    languages: [
      { name: "English", level: "Fluent" },
      { name: "Swahili", level: "Native" },
      { name: "Luo", level: "Native" },
    ],
    workHistory: [
      { title: "Meter box upgrade and safety check", rating: 5, dateRange: "Mar 2025 - Mar 2025", price: "KES 8,500", priceType: "Fixed price" },
    ],
    reviews: [
      { author: "Dorcas A.", rating: 4, comment: "Quick and tidy, would call again." },
    ],
  },
  {
    id: 18,
    name: "Mercy Adhiambo",
    skill: "Carpenter",
    verified: false,
    price: "KES 3,000 – 9,800 / job",
    photo: "https://randomuser.me/api/portraits/women/44.jpg",
    location: "Kondele, Kisumu",
    bio: "Carpentry and furniture repair, with a focus on affordable custom shelving for small homes.",
    rating: 4.2,
    jobSuccess: 89,
    hoursPerWeek: "Less than 30 hrs/week",
    totalEarnings: "KES 140K+",
    jobsCompleted: 10,
    hoursWorked: 300,
    languages: [
      { name: "English", level: "Conversational" },
      { name: "Swahili", level: "Native" },
    ],
    workHistory: [
      { title: "Custom shelving unit", rating: 4, dateRange: "Feb 2025 - Feb 2025", price: "KES 7,200", priceType: "Fixed price" },
    ],
    reviews: [
      { author: "Vincent O.", rating: 4, comment: "Good value, simple honest work." },
    ],
  },
  {
    id: 19,
    name: "Tom Okoth",
    skill: "Painter",
    verified: true,
    price: "KES 2,100 – 8,000 / job",
    photo: "https://randomuser.me/api/portraits/men/6.jpg",
    location: "Mamboleo, Kisumu",
    bio: "Interior and exterior painter, comfortable with both residential and small commercial jobs.",
    rating: 4.6,
    jobSuccess: 96,
    hoursPerWeek: "More than 30 hrs/week",
    totalEarnings: "KES 380K+",
    jobsCompleted: 21,
    hoursWorked: 780,
    languages: [
      { name: "English", level: "Fluent" },
      { name: "Swahili", level: "Native" },
    ],
    workHistory: [
      { title: "Apartment block common areas repaint", rating: 5, dateRange: "Jan 2025 - Feb 2025", price: "KES 26,000", priceType: "Fixed price" },
    ],
    reviews: [
      { author: "Beatrice N.", rating: 5, comment: "Managed a big job well, good crew." },
    ],
  },
  {
    id: 20,
    name: "Naliaka Wafula",
    skill: "Carpenter",
    verified: false,
    price: "KES 4,000 – 12,000 / job",
    photo: "https://randomuser.me/api/portraits/women/30.jpg",
    location: "Section 58, Nakuru",
    bio: "Furniture maker and finish carpenter. I build custom shelves, wardrobes, and doors. I bring samples of past work to every first meeting.",
    rating: 4.3,
    jobSuccess: 90,
    hoursPerWeek: "More than 30 hrs/week",
    totalEarnings: "KES 310K+",
    jobsCompleted: 18,
    hoursWorked: 650,
    languages: [
      { name: "English", level: "Fluent" },
      { name: "Swahili", level: "Native" },
    ],
    workHistory: [
      { title: "Custom wardrobe build", rating: 4, dateRange: "Mar 2025 - Mar 2025", price: "KES 24,000", priceType: "Fixed price" },
      { title: "Panelled door replacement, 3 rooms", rating: 5, dateRange: "Dec 2024 - Dec 2024", price: "KES 15,000", priceType: "Fixed price" },
    ],
    reviews: [
      { author: "Nancy W.", rating: 4, comment: "Beautiful wardrobe, very happy with it." },
      { author: "Caroline A.", rating: 5, comment: "Patient and creative. Highly recommend." },
      { author: "Hassan S.", rating: 4, comment: "Solid build quality." },
    ],
  },
  {
    id: 21,
    name: "Peter Kiplagat",
    skill: "Electrician",
    verified: true,
    price: "KES 2,200 – 7,000 / job",
    photo: "https://randomuser.me/api/portraits/men/50.jpg",
    location: "Milimani, Nakuru",
    bio: "Electrician covering home installations and farmhouse wiring across the Nakuru area.",
    rating: 4.7,
    jobSuccess: 97,
    hoursPerWeek: "More than 30 hrs/week",
    totalEarnings: "KES 470K+",
    jobsCompleted: 24,
    hoursWorked: 860,
    languages: [
      { name: "English", level: "Fluent" },
      { name: "Swahili", level: "Native" },
      { name: "Kalenjin", level: "Native" },
    ],
    workHistory: [
      { title: "Farmhouse wiring and borehole pump connection", rating: 5, dateRange: "Feb 2025 - Mar 2025", price: "KES 21,000", priceType: "Fixed price" },
    ],
    reviews: [
      { author: "Esther C.", rating: 5, comment: "Handled a complicated farm setup with no issues." },
    ],
  },
  {
    id: 22,
    name: "Grace Wambui",
    skill: "Plumber",
    verified: true,
    price: "KES 1,900 – 6,000 / job",
    photo: "https://randomuser.me/api/portraits/women/5.jpg",
    location: "Free Area, Nakuru",
    bio: "Plumbing repairs, water tank installations, and drainage fixes for homes and small offices.",
    rating: 4.4,
    jobSuccess: 93,
    hoursPerWeek: "Less than 30 hrs/week",
    totalEarnings: "KES 210K+",
    jobsCompleted: 16,
    hoursWorked: 520,
    languages: [
      { name: "English", level: "Fluent" },
      { name: "Swahili", level: "Native" },
    ],
    workHistory: [
      { title: "Drainage fix and water tank install", rating: 4, dateRange: "Jan 2025 - Jan 2025", price: "KES 10,500", priceType: "Fixed price" },
    ],
    reviews: [
      { author: "Daniel K.", rating: 4, comment: "Reasonable price and got it right first time." },
    ],
  },
  {
    id: 23,
    name: "Samuel Kimutai",
    skill: "Painter",
    verified: false,
    price: "KES 2,000 – 7,500 / job",
    photo: "https://randomuser.me/api/portraits/men/91.jpg",
    location: "London Estate, Nakuru",
    bio: "Painter offering interior and exterior work, with flexible scheduling for weekend jobs.",
    rating: 4.0,
    jobSuccess: 87,
    hoursPerWeek: "Less than 30 hrs/week",
    totalEarnings: "KES 120K+",
    jobsCompleted: 9,
    hoursWorked: 260,
    languages: [
      { name: "English", level: "Conversational" },
      { name: "Swahili", level: "Native" },
    ],
    workHistory: [
      { title: "Two-bedroom house repaint", rating: 4, dateRange: "Mar 2025 - Mar 2025", price: "KES 13,000", priceType: "Fixed price" },
    ],
    reviews: [
      { author: "Ruth M.", rating: 4, comment: "Did a fair job, took a bit longer than quoted." },
    ],
  },
];

if (typeof window !== "undefined") {
  window.WORKERS = WORKERS;
}
if (typeof module !== "undefined" && module.exports) {
  module.exports = { WORKERS };
}
